services:
  untube:
    build: .
    image: untube
    container_name: untube
    ports:
      - "3987:80"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - DATA_DIR=/app/data
      - DOWNLOADS_DIR=/app/downloads
    restart: unless-stopped
